import shapeData from "../data/shapes.json";

const SHAPES = shapeData as Record<string, string>;

export function hasShape(iso2: string): boolean {
  return iso2 in SHAPES;
}

/**
 * Renders a normalized country silhouette (generated by scripts/build_shapes.mjs).
 * Returns null for the few micro-states with no shape at this map resolution.
 */
export function CountryShape({
  iso2,
  fill = "none",
  stroke = "currentColor",
  strokeWidth = 1.2,
  className = "",
}: {
  iso2: string;
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  className?: string;
}) {
  const d = SHAPES[iso2];
  if (!d) return null;
  return (
    <svg className={`shape ${className}`} viewBox="0 0 100 100" aria-hidden="true">
      <path
        d={d}
        fill={fill}
        stroke={stroke}
        strokeWidth={strokeWidth}
        strokeLinejoin="round"
        vectorEffect="non-scaling-stroke"
      />
    </svg>
  );
}
