#!/usr/bin/env python3
"""
generate_symbols.py  — generate src/data/symbols.json and symbols_uk.json
Run once: python3 scripts/generate_symbols.py
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

EN = {
  "AD": {"animal": "Pyrenean chamois", "plant": "Gran Valira lily", "dish": "Escudella"},
  "AE": {"animal": "Peregrine falcon", "plant": "Date palm", "dish": "Harees"},
  "AF": {"animal": "Snow leopard", "plant": "Tulip", "dish": "Kabuli palau"},
  "AG": {"animal": "Magnificent frigatebird", "plant": "Agave", "dish": "Fungie and pepperpot"},
  "AL": {"animal": "Golden eagle", "plant": "Olive", "dish": "Tavë kosi"},
  "AM": {"animal": "Golden eagle", "plant": "Apricot tree", "dish": "Harissa"},
  "AO": {"animal": "Giant sable antelope", "plant": "Welwitschia", "dish": "Muamba de Galinha"},
  "AR": {"animal": "Puma", "plant": "Ceibo flower", "dish": "Asado"},
  "AT": {"animal": "Barn swallow", "plant": "Edelweiss", "dish": "Wiener Schnitzel"},
  "AU": {"animal": "Red kangaroo", "plant": "Golden wattle", "dish": "Meat pie"},
  "AZ": {"animal": "Karabakh horse", "plant": "Pomegranate", "dish": "Plov"},
  "BA": {"animal": "Brown bear", "plant": "Bosnian lily", "dish": "Bosanski lonac"},
  "BB": {"animal": "Pelican", "plant": "Pride of Barbados", "dish": "Cou-cou and flying fish"},
  "BD": {"animal": "Royal Bengal tiger", "plant": "Water lily", "dish": "Hilsa fish curry"},
  "BE": {"animal": "Lion", "plant": "Red poppy", "dish": "Moules-frites"},
  "BF": {"animal": "Stallion", "plant": "Rosewood", "dish": "Riz gras"},
  "BG": {"animal": "Balkan chamois", "plant": "Rose", "dish": "Banitsa"},
  "BH": {"animal": "Arabian oryx", "plant": "Date palm", "dish": "Machboos"},
  "BI": {"animal": "Lion", "plant": "Sorghum", "dish": "Boko boko harees"},
  "BJ": {"animal": "Leopard", "plant": "Oil palm", "dish": "Kuli-kuli"},
  "BN": {"animal": "Proboscis monkey", "plant": "Simpor", "dish": "Ambuyat"},
  "BO": {"animal": "Llama", "plant": "Patujú flower", "dish": "Salteñas"},
  "BR": {"animal": "Jaguar", "plant": "Cattleya orchid", "dish": "Feijoada"},
  "BS": {"animal": "Flamingo", "plant": "Yellow elder", "dish": "Cracked conch"},
  "BT": {"animal": "Takin", "plant": "Himalayan poppy", "dish": "Ema datshi"},
  "BW": {"animal": "Zebra", "plant": "Mokolwane palm", "dish": "Seswaa"},
  "BY": {"animal": "European bison", "plant": "Flax", "dish": "Draniki"},
  "BZ": {"animal": "Baird's tapir", "plant": "Black orchid", "dish": "Rice and beans"},
  "CA": {"animal": "Beaver", "plant": "Sugar maple", "dish": "Poutine"},
  "CD": {"animal": "Okapi", "plant": "African oil palm", "dish": "Saka-saka"},
  "CF": {"animal": "Elephant", "plant": "Cotton tree", "dish": "Gozo"},
  "CG": {"animal": "Elephant", "plant": "Banana tree", "dish": "Moambe chicken"},
  "CH": {"animal": "Marmot", "plant": "Edelweiss", "dish": "Fondue"},
  "CI": {"animal": "Elephant", "plant": "Oil palm", "dish": "Attiéké"},
  "CL": {"animal": "Andean condor", "plant": "Chilean bellflower", "dish": "Cazuela"},
  "CM": {"animal": "Lion", "plant": "Coffee plant", "dish": "Ndolé"},
  "CN": {"animal": "Giant panda", "plant": "Plum blossom", "dish": "Peking duck"},
  "CO": {"animal": "Andean condor", "plant": "Christmas orchid", "dish": "Bandeja paisa"},
  "CR": {"animal": "Clay-coloured thrush", "plant": "Purple orchid", "dish": "Gallo pinto"},
  "CU": {"animal": "Cuban trogon", "plant": "White mariposa", "dish": "Ropa vieja"},
  "CV": {"animal": "Loggerhead turtle", "plant": "Dragon tree", "dish": "Cachupa"},
  "CY": {"animal": "Moufflon", "plant": "Cyprus cedar", "dish": "Halloumi"},
  "CZ": {"animal": "Double-tailed lion", "plant": "Linden tree", "dish": "Svíčková"},
  "DE": {"animal": "Federal eagle", "plant": "Cornflower", "dish": "Sauerbraten"},
  "DJ": {"animal": "Djibouti francolin", "plant": "Dragon tree", "dish": "Skoudehkaris"},
  "DK": {"animal": "Mute swan", "plant": "Marguerite daisy", "dish": "Smørrebrød"},
  "DM": {"animal": "Sisserou parrot", "plant": "Bwa Kwaib", "dish": "Callaloo"},
  "DO": {"animal": "Palmchat", "plant": "Bayahibe rose", "dish": "La Bandera"},
  "DZ": {"animal": "Fennec fox", "plant": "Broom", "dish": "Couscous"},
  "EC": {"animal": "Andean condor", "plant": "Rose", "dish": "Ceviche"},
  "EE": {"animal": "Barn swallow", "plant": "Cornflower", "dish": "Black bread"},
  "EG": {"animal": "Steppe eagle", "plant": "Lotus", "dish": "Ful medames"},
  "ER": {"animal": "Arabian camel", "plant": "Olive tree", "dish": "Injera"},
  "ES": {"animal": "Bull", "plant": "Carnation", "dish": "Paella"},
  "ET": {"animal": "Lion", "plant": "Calla lily", "dish": "Injera with doro wat"},
  "FI": {"animal": "Whooper swan", "plant": "Lily of the valley", "dish": "Karjalanpiirakka"},
  "FJ": {"animal": "Collared lory", "plant": "Tagimoucia", "dish": "Kokoda"},
  "FM": {"animal": "Micronesian pigeon", "plant": "Ylang-ylang", "dish": "Sakau"},
  "FR": {"animal": "Gallic rooster", "plant": "Iris", "dish": "Pot-au-feu"},
  "GA": {"animal": "Black panther", "plant": "Okoumé tree", "dish": "Nyembwe chicken"},
  "GB": {"animal": "Lion", "plant": "Tudor rose", "dish": "Chicken tikka masala"},
  "GD": {"animal": "Grenada dove", "plant": "Bougainvillea", "dish": "Oil down"},
  "GE": {"animal": "Caucasian leopard", "plant": "Grapevine", "dish": "Khachapuri"},
  "GH": {"animal": "Golden eagle", "plant": "Cocoa tree", "dish": "Fufu"},
  "GM": {"animal": "Spotted hyena", "plant": "Kapok tree", "dish": "Benachin"},
  "GN": {"animal": "Elephant", "plant": "Coffee plant", "dish": "Sauce arachide"},
  "GQ": {"animal": "Elephant", "plant": "Ceiba tree", "dish": "Succotash"},
  "GR": {"animal": "Little owl", "plant": "Olive", "dish": "Moussaka"},
  "GT": {"animal": "Quetzal", "plant": "White nun orchid", "dish": "Pepián"},
  "GW": {"animal": "Roan antelope", "plant": "Mango tree", "dish": "Caldo mancarra"},
  "GY": {"animal": "Jaguar", "plant": "Victoria amazonica", "dish": "Pepperpot"},
  "HN": {"animal": "Scarlet macaw", "plant": "Orchid", "dish": "Baleadas"},
  "HR": {"animal": "Pine marten", "plant": "Iris croatica", "dish": "Peka"},
  "HT": {"animal": "Hispaniolan trogon", "plant": "Amourette", "dish": "Griot"},
  "HU": {"animal": "Turul", "plant": "Tulip", "dish": "Gulyás"},
  "ID": {"animal": "Komodo dragon", "plant": "Jasmine", "dish": "Nasi goreng"},
  "IE": {"animal": "Red deer", "plant": "Shamrock", "dish": "Irish stew"},
  "IL": {"animal": "Mountain gazelle", "plant": "Cyclamen", "dish": "Hummus"},
  "IN": {"animal": "Bengal tiger", "plant": "Lotus", "dish": "Khichdi"},
  "IQ": {"animal": "Chukar partridge", "plant": "Date palm", "dish": "Masgouf"},
  "IR": {"animal": "Persian leopard", "plant": "Persian rose", "dish": "Chelo kabab"},
  "IS": {"animal": "Gyrfalcon", "plant": "Mountain avens", "dish": "Skyr with cream"},
  "IT": {"animal": "Italian wolf", "plant": "Olive", "dish": "Pizza Margherita"},
  "JM": {"animal": "Doctor bird", "plant": "Lignum vitae", "dish": "Ackee and saltfish"},
  "JO": {"animal": "Arabian oryx", "plant": "Black iris", "dish": "Mansaf"},
  "JP": {"animal": "Japanese macaque", "plant": "Cherry blossom", "dish": "Ramen"},
  "KE": {"animal": "Lion", "plant": "Nandi flame tree", "dish": "Ugali"},
  "KG": {"animal": "Snow leopard", "plant": "Absinthe wormwood", "dish": "Beshbarmak"},
  "KH": {"animal": "Kouprey", "plant": "Rumdul flower", "dish": "Amok"},
  "KI": {"animal": "Frigate bird", "plant": "Babai", "dish": "Palusami"},
  "KM": {"animal": "Coelacanth", "plant": "Ylang-ylang", "dish": "Langouste à la vanille"},
  "KN": {"animal": "Brown pelican", "plant": "Poinciana", "dish": "Stewed saltfish"},
  "KP": {"animal": "Chollima", "plant": "Magnolia", "dish": "Sinsollo"},
  "KR": {"animal": "Siberian tiger", "plant": "Hibiscus", "dish": "Kimchi"},
  "KW": {"animal": "Falcon", "plant": "Arfaj", "dish": "Machboos"},
  "KZ": {"animal": "Snow leopard", "plant": "Saksaul", "dish": "Beshbarmak"},
  "LA": {"animal": "Asian elephant", "plant": "Dok Champa", "dish": "Laap"},
  "LB": {"animal": "Striped hyena", "plant": "Cedar of Lebanon", "dish": "Kibbeh"},
  "LC": {"animal": "Saint Lucia parrot", "plant": "Marguerite", "dish": "Green fig and saltfish"},
  "LI": {"animal": "Brown trout", "plant": "Oak", "dish": "Käsknöpfle"},
  "LK": {"animal": "Sri Lanka junglefowl", "plant": "Blue lotus", "dish": "Rice and curry"},
  "LR": {"animal": "Pygmy hippopotamus", "plant": "Pepper tree", "dish": "Palm butter soup"},
  "LS": {"animal": "Basotho pony", "plant": "Spiral aloe", "dish": "Pap"},
  "LT": {"animal": "White stork", "plant": "Rue", "dish": "Cepelinai"},
  "LU": {"animal": "Red lion", "plant": "Moselle rose", "dish": "Judd mat Gaardebounen"},
  "LV": {"animal": "White wagtail", "plant": "Daisy", "dish": "Grey peas with bacon"},
  "LY": {"animal": "Arabian eagle", "plant": "Oleander", "dish": "Couscous"},
  "MA": {"animal": "Barbary lion", "plant": "Argan tree", "dish": "Tagine"},
  "MC": {"animal": "Hedgehog", "plant": "Carnation", "dish": "Barbajuan"},
  "MD": {"animal": "Aurochs", "plant": "Stefanesti vine", "dish": "Mămăligă"},
  "ME": {"animal": "Golden eagle", "plant": "Sweet olive", "dish": "Kacamak"},
  "MG": {"animal": "Ring-tailed lemur", "plant": "Traveller's palm", "dish": "Romazava"},
  "MH": {"animal": "Frigate bird", "plant": "Iu", "dish": "Coconut crab"},
  "MK": {"animal": "Lynx", "plant": "Red poppy", "dish": "Tavče gravče"},
  "ML": {"animal": "Hippopotamus", "plant": "Shea tree", "dish": "Tô"},
  "MM": {"animal": "Green peafowl", "plant": "Padauk", "dish": "Mohinga"},
  "MN": {"animal": "Takhi horse", "plant": "Soyombo flower", "dish": "Khorkhog"},
  "MR": {"animal": "Addax", "plant": "Date palm", "dish": "Thiéboudienne"},
  "MT": {"animal": "Maltese falcon", "plant": "Maltese centaury", "dish": "Stuffat tal-Fenek"},
  "MU": {"animal": "Dodo (historical)", "plant": "Trochetia boutoniana", "dish": "Dholl puri"},
  "MV": {"animal": "Yellowfin tuna", "plant": "Coconut palm", "dish": "Garudhiya"},
  "MW": {"animal": "African fish eagle", "plant": "Mulanje cedar", "dish": "Nsima"},
  "MX": {"animal": "Golden eagle", "plant": "Dahlia", "dish": "Tacos"},
  "MY": {"animal": "Malayan tiger", "plant": "Hibiscus", "dish": "Nasi lemak"},
  "MZ": {"animal": "African elephant", "plant": "Flame lily", "dish": "Matapa"},
  "NA": {"animal": "Oryx", "plant": "Kokerboom", "dish": "Potjiekos"},
  "NE": {"animal": "Addax", "plant": "Desert date", "dish": "Djerma stew"},
  "NG": {"animal": "Eagle", "plant": "Costus afer", "dish": "Egusi soup"},
  "NI": {"animal": "Turquoise-browed motmot", "plant": "Sacuanjoche", "dish": "Gallo pinto"},
  "NL": {"animal": "Lion", "plant": "Tulip", "dish": "Stamppot"},
  "NO": {"animal": "Lion", "plant": "Purple heather", "dish": "Fårikål"},
  "NP": {"animal": "Cow", "plant": "Rhododendron", "dish": "Dal bhat"},
  "NR": {"animal": "Frigate bird", "plant": "Calophyllum inophyllum", "dish": "Coconut fish"},
  "NZ": {"animal": "Kiwi", "plant": "Silver fern", "dish": "Hangi"},
  "OM": {"animal": "Arabian oryx", "plant": "Frankincense tree", "dish": "Shuwa"},
  "PA": {"animal": "Harpy eagle", "plant": "Holy Ghost orchid", "dish": "Sancocho"},
  "PE": {"animal": "Andean condor", "plant": "Cantuta", "dish": "Ceviche"},
  "PG": {"animal": "Raggiana bird-of-paradise", "plant": "Lakatoi orchid", "dish": "Mumu"},
  "PH": {"animal": "Philippine eagle", "plant": "Sampaguita", "dish": "Adobo"},
  "PK": {"animal": "Markhor", "plant": "Jasmine", "dish": "Biryani"},
  "PL": {"animal": "White-tailed eagle", "plant": "Corn poppy", "dish": "Bigos"},
  "PS": {"animal": "Palestine sunbird", "plant": "Olive tree", "dish": "Musakhan"},
  "PT": {"animal": "Iberian wolf", "plant": "Lavender", "dish": "Bacalhau"},
  "PW": {"animal": "Dugong", "plant": "Plumeria", "dish": "Taro"},
  "PY": {"animal": "Pampas fox", "plant": "Mburucuyá", "dish": "Sopa paraguaya"},
  "QA": {"animal": "Arabian oryx", "plant": "Sidder tree", "dish": "Machboos"},
  "RO": {"animal": "Lynx", "plant": "Dog rose", "dish": "Sarmale"},
  "RS": {"animal": "White eagle", "plant": "Hops", "dish": "Sarma"},
  "RU": {"animal": "Russian brown bear", "plant": "Chamomile", "dish": "Borscht"},
  "RW": {"animal": "Nile crocodile", "plant": "Inshuti flower", "dish": "Isombe"},
  "SA": {"animal": "Arabian oryx", "plant": "Date palm", "dish": "Kabsa"},
  "SB": {"animal": "Frigate bird", "plant": "Canarium", "dish": "Roasted yam"},
  "SC": {"animal": "Aldabra giant tortoise", "plant": "Coco de mer", "dish": "Grilled fish"},
  "SD": {"animal": "Secretary bird", "plant": "Date palm", "dish": "Ful medames"},
  "SE": {"animal": "Eurasian elk", "plant": "Linnaea", "dish": "Köttbullar"},
  "SG": {"animal": "Lion", "plant": "Vanda Miss Joaquim", "dish": "Chicken rice"},
  "SI": {"animal": "Proteus", "plant": "Red carnation", "dish": "Kranjska klobasa"},
  "SK": {"animal": "Tatra chamois", "plant": "Lime tree", "dish": "Bryndzové halušky"},
  "SL": {"animal": "Lion", "plant": "Oil palm", "dish": "Groundnut soup"},
  "SM": {"animal": "Brown trout", "plant": "Star of Bethlehem", "dish": "Piadina"},
  "SN": {"animal": "Lion", "plant": "Baobab", "dish": "Thiéboudienne"},
  "SO": {"animal": "Leopard", "plant": "Frankincense tree", "dish": "Canjeero"},
  "SR": {"animal": "Jaguar", "plant": "Faya lobi flower", "dish": "Pom"},
  "SS": {"animal": "Shoebill stork", "plant": "Teak tree", "dish": "Ful medames"},
  "ST": {"animal": "São Tomé green ibis", "plant": "Cocoa tree", "dish": "Calulu"},
  "SV": {"animal": "Turquoise-browed motmot", "plant": "Izote", "dish": "Pupusas"},
  "SY": {"animal": "Arabian eagle", "plant": "Jasmine", "dish": "Kibbeh"},
  "SZ": {"animal": "Purple-crested turaco", "plant": "Sugarcane", "dish": "Incwancwa"},
  "TD": {"animal": "Arabian horse", "plant": "Acacia", "dish": "Daraba"},
  "TG": {"animal": "Dove", "plant": "Oil palm", "dish": "Akoumé"},
  "TH": {"animal": "Asian elephant", "plant": "Ratchaphruek", "dish": "Pad Thai"},
  "TJ": {"animal": "Snow leopard", "plant": "Pomegranate", "dish": "Osh"},
  "TL": {"animal": "Saltwater crocodile", "plant": "Sandalwood", "dish": "Ikan saboko"},
  "TM": {"animal": "Akhal-Teke horse", "plant": "Seyr tree", "dish": "Plov"},
  "TN": {"animal": "Sand gazelle", "plant": "Olive tree", "dish": "Couscous"},
  "TO": {"animal": "Tongan ground dove", "plant": "Heilala", "dish": "Otai"},
  "TR": {"animal": "Grey wolf", "plant": "Tulip", "dish": "Döner kebab"},
  "TT": {"animal": "Scarlet ibis", "plant": "Chaconia", "dish": "Doubles"},
  "TV": {"animal": "Frigate bird", "plant": "Pukaraga", "dish": "Pulaka"},
  "TZ": {"animal": "Giraffe", "plant": "Clove tree", "dish": "Ugali"},
  "UA": {"animal": "White stork", "plant": "Sunflower", "dish": "Borscht"},
  "UG": {"animal": "Grey crowned crane", "plant": "Coffee plant", "dish": "Matooke"},
  "US": {"animal": "Bald eagle", "plant": "Oak", "dish": "Apple pie"},
  "UY": {"animal": "Southern lapwing", "plant": "Ceibo flower", "dish": "Asado"},
  "UZ": {"animal": "Snow leopard", "plant": "White poplar", "dish": "Plov"},
  "VA": {"animal": "Roman eagle", "plant": "White lily", "dish": "Saltimbocca"},
  "VC": {"animal": "Saint Vincent parrot", "plant": "Soufrière tree", "dish": "Roasted breadfruit"},
  "VE": {"animal": "Troupial", "plant": "Cattleya orchid", "dish": "Pabellón criollo"},
  "VN": {"animal": "Water buffalo", "plant": "Lotus", "dish": "Phở"},
  "VU": {"animal": "Coconut crab", "plant": "Namele fern", "dish": "Lap lap"},
  "WS": {"animal": "Tooth-billed pigeon", "plant": "Teuila", "dish": "Palusami"},
  "YE": {"animal": "Arabian leopard", "plant": "Coffee plant", "dish": "Saltah"},
  "ZA": {"animal": "Springbok", "plant": "King protea", "dish": "Braai"},
  "ZM": {"animal": "African fish eagle", "plant": "Flame lily", "dish": "Nshima"},
  "ZW": {"animal": "Sable antelope", "plant": "Flame lily", "dish": "Sadza"},
}

UK = {
  "AD": {"animal": "Піренейська серна", "plant": "Ліліяграновалір", "dish": "Ескуделья"},
  "AE": {"animal": "Сапсан", "plant": "Фінікова пальма", "dish": "Харіс"},
  "AF": {"animal": "Сніговий барс", "plant": "Тюльпан", "dish": "Кабулі палав"},
  "AG": {"animal": "Великий фрегат", "plant": "Агава", "dish": "Фанджі з перцевим горщиком"},
  "AL": {"animal": "Золотий орел", "plant": "Оливкове дерево", "dish": "Тавє косі"},
  "AM": {"animal": "Золотий орел", "plant": "Абрикосове дерево", "dish": "Хариса"},
  "AO": {"animal": "Гігантська соболева антилопа", "plant": "Вельвічія", "dish": "Муамба де Галінья"},
  "AR": {"animal": "Пума", "plant": "Квітка цейба", "dish": "Асадо"},
  "AT": {"animal": "Міська ластівка", "plant": "Едельвейс", "dish": "Вінерський шніцель"},
  "AU": {"animal": "Рудий кенгуру", "plant": "Золота акація", "dish": "М'ясний пиріг"},
  "AZ": {"animal": "Карабаський кінь", "plant": "Гранат", "dish": "Плов"},
  "BA": {"animal": "Бурий ведмідь", "plant": "Боснійська лілія", "dish": "Боснійський лонац"},
  "BB": {"animal": "Пелікан", "plant": "Краса Барбадосу", "dish": "Ку-ку з летючою рибою"},
  "BD": {"animal": "Бенгальський тигр", "plant": "Водяна лілія", "dish": "Хілса карі"},
  "BE": {"animal": "Лев", "plant": "Червоний мак", "dish": "Мідії з картоплею фрі"},
  "BF": {"animal": "Жеребець", "plant": "Рожеве дерево", "dish": "Рі гра"},
  "BG": {"animal": "Балканська серна", "plant": "Троянда", "dish": "Баниця"},
  "BH": {"animal": "Аравійський орикс", "plant": "Фінікова пальма", "dish": "Махбус"},
  "BI": {"animal": "Лев", "plant": "Сорго", "dish": "Боко боко харіс"},
  "BJ": {"animal": "Леопард", "plant": "Олійна пальма", "dish": "Кулі-кулі"},
  "BN": {"animal": "Носач", "plant": "Сімпор", "dish": "Амбуят"},
  "BO": {"animal": "Лама", "plant": "Квітка патуху", "dish": "Сальтеньяс"},
  "BR": {"animal": "Ягуар", "plant": "Орхідея каттлея", "dish": "Фейжоада"},
  "BS": {"animal": "Рожевий фламінго", "plant": "Жовта бузина", "dish": "Смажений равлик-трубач"},
  "BT": {"animal": "Такін", "plant": "Гімалайський мак", "dish": "Єма датші"},
  "BW": {"animal": "Зебра", "plant": "Пальма моколвейн", "dish": "Сесва"},
  "BY": {"animal": "Зубр", "plant": "Льон", "dish": "Деруни"},
  "BZ": {"animal": "Тапір Байрда", "plant": "Чорна орхідея", "dish": "Рис з квасолею"},
  "CA": {"animal": "Бобер", "plant": "Цукровий клен", "dish": "Путін"},
  "CD": {"animal": "Окапі", "plant": "Олійна пальма", "dish": "Сака-сака"},
  "CF": {"animal": "Слон", "plant": "Бавовникове дерево", "dish": "Гозо"},
  "CG": {"animal": "Слон", "plant": "Бананове дерево", "dish": "Курка мвамбе"},
  "CH": {"animal": "Альпійський бабак", "plant": "Едельвейс", "dish": "Фондю"},
  "CI": {"animal": "Слон", "plant": "Олійна пальма", "dish": "Аттієке"},
  "CL": {"animal": "Андійський кондор", "plant": "Чилійський дзвіночок", "dish": "Касуела"},
  "CM": {"animal": "Лев", "plant": "Кавове дерево", "dish": "Ндоле"},
  "CN": {"animal": "Велика панда", "plant": "Цвіт сливи", "dish": "Качка по-пекінськи"},
  "CO": {"animal": "Андійський кондор", "plant": "Орхідея різдвяна", "dish": "Бандеха паїса"},
  "CR": {"animal": "Строкатодзьоб", "plant": "Фіолетова орхідея", "dish": "Гало пінто"},
  "CU": {"animal": "Кубинський трогон", "plant": "Біла маріпоса", "dish": "Ропа вієха"},
  "CV": {"animal": "Каретта-каретта", "plant": "Драконове дерево", "dish": "Кашупа"},
  "CY": {"animal": "Муфлон", "plant": "Кіпрський кедр", "dish": "Халумі"},
  "CZ": {"animal": "Двохвостий лев", "plant": "Липа", "dish": "Свічкова"},
  "DE": {"animal": "Федеральний орел", "plant": "Волошка", "dish": "Зауербратен"},
  "DJ": {"animal": "Джибутійський турач", "plant": "Драконове дерево", "dish": "Скудехкаріс"},
  "DK": {"animal": "Лебідь-шипун", "plant": "Маргаритка", "dish": "Смерреброд"},
  "DM": {"animal": "Папуга сісеру", "plant": "Бва-кваїб", "dish": "Каллалу"},
  "DO": {"animal": "Пальмовий чатак", "plant": "Троянда байяхіби", "dish": "Ла Бандера"},
  "DZ": {"animal": "Фенек", "plant": "Дрік", "dish": "Кускус"},
  "EC": {"animal": "Андійський кондор", "plant": "Троянда", "dish": "Севіче"},
  "EE": {"animal": "Сільська ластівка", "plant": "Волошка", "dish": "Чорний хліб"},
  "EG": {"animal": "Степовий орел", "plant": "Лотос", "dish": "Фул мадамес"},
  "ER": {"animal": "Аравійський верблюд", "plant": "Оливкове дерево", "dish": "Ін'єра"},
  "ES": {"animal": "Бик", "plant": "Гвоздика", "dish": "Паелья"},
  "ET": {"animal": "Лев", "plant": "Кала-лілея", "dish": "Ін'єра з куркою доро"},
  "FI": {"animal": "Лебідь-кликун", "plant": "Конвалія", "dish": "Карельський пиріжок"},
  "FJ": {"animal": "Пістряволорі", "plant": "Квітка тагімоуція", "dish": "Кокода"},
  "FM": {"animal": "Мікронезійський голуб", "plant": "Іланг-іланг", "dish": "Сакау"},
  "FR": {"animal": "Галльський півень", "plant": "Ірис", "dish": "Пот-о-фе"},
  "GA": {"animal": "Чорна пантера", "plant": "Дерево окуме", "dish": "Курка ньємбве"},
  "GB": {"animal": "Лев", "plant": "Тюдорська троянда", "dish": "Курка тіка масала"},
  "GD": {"animal": "Гренадський голуб", "plant": "Бугенвілея", "dish": "Олл-даун"},
  "GE": {"animal": "Кавказький леопард", "plant": "Виноградна лоза", "dish": "Хачапурі"},
  "GH": {"animal": "Золотий орел", "plant": "Дерево какао", "dish": "Фуфу"},
  "GM": {"animal": "Плямиста гієна", "plant": "Хлопкове дерево", "dish": "Бенашін"},
  "GN": {"animal": "Слон", "plant": "Кавове дерево", "dish": "Арахісовий соус"},
  "GQ": {"animal": "Слон", "plant": "Дерево сейба", "dish": "Сукоташ"},
  "GR": {"animal": "Маленька сова", "plant": "Оливкове дерево", "dish": "Мусака"},
  "GT": {"animal": "Кетсаль", "plant": "Орхідея біла черниця", "dish": "Пепіан"},
  "GW": {"animal": "Кобрина антилопа", "plant": "Дерево манго", "dish": "Кальдо манкарра"},
  "GY": {"animal": "Ягуар", "plant": "Вікторія амазонська", "dish": "Пепер-пот"},
  "HN": {"animal": "Шарлатова макава", "plant": "Орхідея", "dish": "Балеадас"},
  "HR": {"animal": "Кам'яна куниця", "plant": "Хорватський ірис", "dish": "Пека"},
  "HT": {"animal": "Гаїтянський трогон", "plant": "Амурет", "dish": "Гріо"},
  "HU": {"animal": "Турул", "plant": "Тюльпан", "dish": "Гуляш"},
  "ID": {"animal": "Комодський варан", "plant": "Жасмін", "dish": "Насі-горенг"},
  "IE": {"animal": "Благородний олень", "plant": "Конюшина", "dish": "Ірландське рагу"},
  "IL": {"animal": "Гірська газель", "plant": "Цикламен", "dish": "Хумус"},
  "IN": {"animal": "Бенгальський тигр", "plant": "Лотос", "dish": "Кхічді"},
  "IQ": {"animal": "Куріпка чукар", "plant": "Фінікова пальма", "dish": "Мазгуф"},
  "IR": {"animal": "Перський леопард", "plant": "Перська троянда", "dish": "Чело-кебаб"},
  "IS": {"animal": "Кречет", "plant": "Дріада восьмипелюсткова", "dish": "Скір з вершками"},
  "IT": {"animal": "Апеннінський вовк", "plant": "Оливкове дерево", "dish": "Піца Маргарита"},
  "JM": {"animal": "Пурпурна юла", "plant": "Гуаякове дерево", "dish": "Акі з солоною тріскою"},
  "JO": {"animal": "Аравійський орикс", "plant": "Чорний ірис", "dish": "Мансаф"},
  "JP": {"animal": "Японський макак", "plant": "Сакура", "dish": "Рамен"},
  "KE": {"animal": "Лев", "plant": "Нанді вогняне дерево", "dish": "Угалі"},
  "KG": {"animal": "Сніговий барс", "plant": "Гіркий полин", "dish": "Бешбармак"},
  "KH": {"animal": "Купрей", "plant": "Квітка румдул", "dish": "Амок"},
  "KI": {"animal": "Фрегат", "plant": "Бабай", "dish": "Палусамі"},
  "KM": {"animal": "Латимерія", "plant": "Іланг-іланг", "dish": "Омар у ванілі"},
  "KN": {"animal": "Бурий пелікан", "plant": "Пуансетія", "dish": "Тушкована солона риба"},
  "KP": {"animal": "Чолліма", "plant": "Магнолія", "dish": "Сінсолло"},
  "KR": {"animal": "Сибірський тигр", "plant": "Гібіскус", "dish": "Кімчі"},
  "KW": {"animal": "Сокіл", "plant": "Арфадж", "dish": "Махбус"},
  "KZ": {"animal": "Сніговий барс", "plant": "Саксаул", "dish": "Бешбармак"},
  "LA": {"animal": "Азіатський слон", "plant": "Квітка чампа", "dish": "Лаап"},
  "LB": {"animal": "Смугаста гієна", "plant": "Ліванський кедр", "dish": "Кіббе"},
  "LC": {"animal": "Папуга Сент-Лусії", "plant": "Маргаритка", "dish": "Зелений інжир з тріскою"},
  "LI": {"animal": "Струмкова форель", "plant": "Дуб", "dish": "Кеснепфле"},
  "LK": {"animal": "Цейлонська джунглева курка", "plant": "Блакитний лотос", "dish": "Рис з каррі"},
  "LR": {"animal": "Карликовий бегемот", "plant": "Перцеве дерево", "dish": "Суп з олійної пальми"},
  "LS": {"animal": "Басутський поні", "plant": "Спіральне алое", "dish": "Пап"},
  "LT": {"animal": "Білий лелека", "plant": "Рута", "dish": "Цепеліни"},
  "LU": {"animal": "Червоний лев", "plant": "Троянда Мозелю", "dish": "Юдд з горохом"},
  "LV": {"animal": "Біла плиска", "plant": "Ромашка", "dish": "Копчений горох з беконом"},
  "LY": {"animal": "Аравійський орел", "plant": "Олеандр", "dish": "Кускус"},
  "MA": {"animal": "Берберійський лев", "plant": "Аргановане дерево", "dish": "Таджин"},
  "MC": {"animal": "Їжак", "plant": "Гвоздика", "dish": "Барбажуан"},
  "MD": {"animal": "Тур", "plant": "Виноград Стефанешти", "dish": "Мамалига"},
  "ME": {"animal": "Золотий орел", "plant": "Маслина", "dish": "Качамак"},
  "MG": {"animal": "Кільцехвостий лемур", "plant": "Пальма мандрівника", "dish": "Ромазава"},
  "MH": {"animal": "Фрегат", "plant": "Йю", "dish": "Кокосовий краб"},
  "MK": {"animal": "Рись", "plant": "Червоний мак", "dish": "Тавче гравче"},
  "ML": {"animal": "Бегемот", "plant": "Дерево шеа", "dish": "То"},
  "MM": {"animal": "Зелений павич", "plant": "Падаук", "dish": "Мохінга"},
  "MN": {"animal": "Дикий кінь такхі", "plant": "Квітка соємбо", "dish": "Хорхог"},
  "MR": {"animal": "Адакс", "plant": "Фінікова пальма", "dish": "Тьєбудієн"},
  "MT": {"animal": "Мальтійський сокіл", "plant": "Центаурея мальтійська", "dish": "Тушкований кролик"},
  "MU": {"animal": "Дронт (нині вимер)", "plant": "Трохеція Бутона", "dish": "Дхол пурі"},
  "MV": {"animal": "Жовтоперий тунець", "plant": "Кокосова пальма", "dish": "Гарудія"},
  "MW": {"animal": "Африканський рибалочник", "plant": "Кедр Муланже", "dish": "Нсіма"},
  "MX": {"animal": "Золотий орел", "plant": "Жоржина", "dish": "Тако"},
  "MY": {"animal": "Малайський тигр", "plant": "Гібіскус", "dish": "Насі лемак"},
  "MZ": {"animal": "Африканський слон", "plant": "Вогняна лілія", "dish": "Матапа"},
  "NA": {"animal": "Орикс", "plant": "Колчанне дерево", "dish": "Потйєкос"},
  "NE": {"animal": "Адакс", "plant": "Пустельний фінік", "dish": "Страви Джерма"},
  "NG": {"animal": "Орел", "plant": "Костус африканський", "dish": "Суп з насіння гарбуза"},
  "NI": {"animal": "Мотмот", "plant": "Сакуанхоче", "dish": "Гало пінто"},
  "NL": {"animal": "Лев", "plant": "Тюльпан", "dish": "Штампот"},
  "NO": {"animal": "Лев", "plant": "Верес звичайний", "dish": "Фаріколь"},
  "NP": {"animal": "Корова", "plant": "Рododendron", "dish": "Дал бат"},
  "NR": {"animal": "Фрегат", "plant": "Каллофілум", "dish": "Кокосова риба"},
  "NZ": {"animal": "Ківі", "plant": "Срібна папороть", "dish": "Хангі"},
  "OM": {"animal": "Аравійський орикс", "plant": "Ладанне дерево", "dish": "Шуа"},
  "PA": {"animal": "Гарпія", "plant": "Орхідея Святого Духа", "dish": "Санкочо"},
  "PE": {"animal": "Андійський кондор", "plant": "Кантута", "dish": "Севіче"},
  "PG": {"animal": "Птах раю рагіана", "plant": "Орхідея лакатої", "dish": "Муму"},
  "PH": {"animal": "Філіппінський орел", "plant": "Сампагіта", "dish": "Адобо"},
  "PK": {"animal": "Маркхор", "plant": "Жасмін", "dish": "Біряні"},
  "PL": {"animal": "Орлан-білохвіст", "plant": "Волошка", "dish": "Бігос"},
  "PS": {"animal": "Палестинська нектарниця", "plant": "Оливкове дерево", "dish": "Мусахан"},
  "PT": {"animal": "Іберійський вовк", "plant": "Лаванда", "dish": "Бакаляу"},
  "PW": {"animal": "Дюгонь", "plant": "Плюмерія", "dish": "Таро"},
  "PY": {"animal": "Пампасна лисиця", "plant": "Мбуруку", "dish": "Сопа парагвайська"},
  "QA": {"animal": "Аравійський орикс", "plant": "Сідерське дерево", "dish": "Махбус"},
  "RO": {"animal": "Рись", "plant": "Шипшина", "dish": "Сармале"},
  "RS": {"animal": "Білий орел", "plant": "Хміль", "dish": "Сарма"},
  "RU": {"animal": "Бурий ведмідь", "plant": "Ромашка", "dish": "Борщ"},
  "RW": {"animal": "Нільський крокодил", "plant": "Квітка іншуті", "dish": "Ізомбе"},
  "SA": {"animal": "Аравійський орикс", "plant": "Фінікова пальма", "dish": "Кабса"},
  "SB": {"animal": "Фрегат", "plant": "Канаріум", "dish": "Смажений ямс"},
  "SC": {"animal": "Гігантська черепаха альдабра", "plant": "Коко де мер", "dish": "Смажена риба"},
  "SD": {"animal": "Птах-секретар", "plant": "Фінікова пальма", "dish": "Фул мадамес"},
  "SE": {"animal": "Лось", "plant": "Ліннея", "dish": "Фрикадельки"},
  "SG": {"animal": "Лев", "plant": "Ванда Міс Хоакін", "dish": "Курка по-сінгапурськи"},
  "SI": {"animal": "Протей", "plant": "Червона гвоздика", "dish": "Крайнська ковбаса"},
  "SK": {"animal": "Татрянська серна", "plant": "Липа", "dish": "Брундзові галушки"},
  "SL": {"animal": "Лев", "plant": "Олійна пальма", "dish": "Арахісовий суп"},
  "SM": {"animal": "Струмкова форель", "plant": "Зірка Віфлеєму", "dish": "П'ядіна"},
  "SN": {"animal": "Лев", "plant": "Баобаб", "dish": "Тьєбудієн"},
  "SO": {"animal": "Леопард", "plant": "Ладанне дерево", "dish": "Канджеро"},
  "SR": {"animal": "Ягуар", "plant": "Квітка фаялобі", "dish": "Пом"},
  "SS": {"animal": "Шолохвіст", "plant": "Тикове дерево", "dish": "Фул мадамес"},
  "ST": {"animal": "Зелений ібіс Сан-Томе", "plant": "Дерево какао", "dish": "Калулу"},
  "SV": {"animal": "Бірюзовочолий мотмот", "plant": "Ізоте", "dish": "Пупуси"},
  "SY": {"animal": "Аравійський орел", "plant": "Жасмін", "dish": "Кіббе"},
  "SZ": {"animal": "Фіолетовочубий тюрако", "plant": "Цукрова тростина", "dish": "Інцванцва"},
  "TD": {"animal": "Аравійський кінь", "plant": "Акація", "dish": "Дараба"},
  "TG": {"animal": "Голуб", "plant": "Олійна пальма", "dish": "Акуме"},
  "TH": {"animal": "Азіатський слон", "plant": "Ратчапруек", "dish": "Пад-Тай"},
  "TJ": {"animal": "Сніговий барс", "plant": "Гранат", "dish": "Ош"},
  "TL": {"animal": "Гребінчастий крокодил", "plant": "Сандалове дерево", "dish": "Ікан сабоко"},
  "TM": {"animal": "Ахалтекінський кінь", "plant": "Полин сейр", "dish": "Плов"},
  "TN": {"animal": "Пісочна газель", "plant": "Оливкове дерево", "dish": "Кускус"},
  "TO": {"animal": "Тонганський наземний голуб", "plant": "Хейлала", "dish": "Отай"},
  "TR": {"animal": "Сірий вовк", "plant": "Тюльпан", "dish": "Дьонер-кебаб"},
  "TT": {"animal": "Алий ібіс", "plant": "Чаконія", "dish": "Даблс"},
  "TV": {"animal": "Фрегат", "plant": "Пукарага", "dish": "Пулака"},
  "TZ": {"animal": "Жираф", "plant": "Гвоздичне дерево", "dish": "Угалі"},
  "UA": {"animal": "Білий лелека", "plant": "Соняшник", "dish": "Борщ"},
  "UG": {"animal": "Сірий чубатий журавель", "plant": "Кавове дерево", "dish": "Матоке"},
  "US": {"animal": "Білоголовий орлан", "plant": "Дуб", "dish": "Яблучний пиріг"},
  "UY": {"animal": "Чайок південний", "plant": "Квітка цейба", "dish": "Асадо"},
  "UZ": {"animal": "Сніговий барс", "plant": "Біла тополя", "dish": "Плов"},
  "VA": {"animal": "Римський орел", "plant": "Біла лілія", "dish": "Сальтімбокка"},
  "VC": {"animal": "Папуга Сент-Вінсента", "plant": "Дерево суфрієр", "dish": "Смажене хлібне дерево"},
  "VE": {"animal": "Трупіал", "plant": "Орхідея каттлея", "dish": "Павільон кріоло"},
  "VN": {"animal": "Водяний буйвіл", "plant": "Лотос", "dish": "Фо"},
  "VU": {"animal": "Кокосовий краб", "plant": "Папороть намеле", "dish": "Лап-лап"},
  "WS": {"animal": "Зубчастий голуб", "plant": "Квітка тейла", "dish": "Палусамі"},
  "YE": {"animal": "Аравійський леопард", "plant": "Кавове дерево", "dish": "Салта"},
  "ZA": {"animal": "Спрингбок", "plant": "Королівська протея", "dish": "Браай"},
  "ZM": {"animal": "Африканський рибалочник", "plant": "Вогняна лілія", "dish": "Нші"},
  "ZW": {"animal": "Соболева антилопа", "plant": "Вогняна лілія", "dish": "Садза"},
}

out_en = os.path.join(ROOT, "src", "data", "symbols.json")
out_uk = os.path.join(ROOT, "src", "data", "symbols_uk.json")

with open(out_en, "w", encoding="utf-8") as f:
    json.dump(EN, f, ensure_ascii=False, indent=2)

with open(out_uk, "w", encoding="utf-8") as f:
    json.dump(UK, f, ensure_ascii=False, indent=2)

print(f"EN: {len(EN)} entries -> {out_en}")
print(f"UK: {len(UK)} entries -> {out_uk}")
